vim.keymap.set("n", "<leader>gb", ":G blame<cr>")
vim.keymap.set("n", "<leader>gc", ":G commit<cr>")
vim.keymap.set("n", "<leader>gd", ":Gvdiffsplit<cr>")
vim.keymap.set("n", "<leader>gg", ":G ")
vim.keymap.set("n", "<leader>gk", ":G checkout ")
vim.keymap.set("n", "<leader>gl", ":G log<cr>")
vim.keymap.set("n", "<leader>gm", ":G commit -m ")
vim.keymap.set("n", "<leader>gn", ":G branch ")
vim.keymap.set("n", "<leader>go", ":G push --set-upstream origin ")
vim.keymap.set("n", "<leader>gp", ":G pull<cr>")
vim.keymap.set("n", "<leader>gr", ":G rebase ")
vim.keymap.set("n", "<leader>gs", ":G<cr>")
vim.keymap.set("n", "<leader>gu", ":G push<cr>")
vim.keymap.set("n", "<leader>gw", ":Gwrite<cr>")
