vim.keymap.set("n", "<leader>gb", ":G blame<cr>")
vim.keymap.set("n", "<leader>gc", ":G commit<cr>")
vim.keymap.set("n", "<leader>gd", ":Gvdiffsplit<cr>")
vim.keymap.set("n", "<leader>gg", ":G ")
vim.keymap.set("n", "<leader>gk", ":G checkout ")
vim.keymap.set("n", "<leader>gl", ":G log")
vim.keymap.set("n", "<leader>gm", ":G commit -m ")
vim.keymap.set("n", "<leader>gn", ":G branch ")
vim.keymap.set("n", "<leader>gpn", ":G pull<cr>")
vim.keymap.set("n", "<leader>gpr", ":G pull --rebase<cr>")
vim.keymap.set("n", "<leader>gpp", ":G push<cr>")
vim.keymap.set("n", "<leader>gps", ":G push --set-upstream origin ")
vim.keymap.set("n", "<leader>gr", ":G rebase ")
vim.keymap.set("n", "<leader>gs", ":G<cr>")
