require("core.plugin_config.cmp")
require("core.plugin_config.comment")
require("core.plugin_config.lsp")
require("core.plugin_config.movement")
require("core.plugin_config.theme")
require("core.plugin_config.toggle-term")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
